// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxtprpumkdvgfxyigfdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4dHBycHVta2R2Z2Z4eWlnZmRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MDg0MzQsImV4cCI6MjA2MzI4NDQzNH0.jczP0mG0bQVqWMWSM48hWKWKdsg_bqG3G2xnWpF30zQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);